package com.d3t.citybuilder;

public enum ItemClickEvents {
	
	NONE(0),
	CONFIRM_ACTION(1),
	CANCEL_ACTION(2),
	ZONE_TOOL(3),
	BUILD_TOOL(4),
	BULLDOZE_TOOL(5),
	PROTECT_TOOL(6),
	INFORMATION_TOOL(7),
	OPEN_EDITOR(98),
	BACK(99),
	ZONETYPE_NONE(20),
	ZONETYPE_TRANSPORT(21),
	ZONETYPE_NOBUILD(22),
	ZONETYPE_ADMINISTRATION(23),
	ZONETYPE_RESIDENTAL(30),
	ZONETYPE_RESIDENTAL_LOW(31),
	ZONETYPE_RESIDENTAL_MED(32),
	ZONETYPE_RESIDENTAL_HIGH(33),
	ZONETYPE_RESIDENTAL_CUSTOM(34),
	ZONETYPE_RETAIL(35),
	ZONETYPE_RETAIL_LOW(36),
	ZONETYPE_RETAIL_MED(37),
	ZONETYPE_RETAIL_CUSTOM(39),
	ZONETYPE_OFFICE(40),
	ZONETYPE_OFFICE_MED(42),
	ZONETYPE_OFFICE_HIGH(43),
	ZONETYPE_OFFICE_CUSTOM(44),
	ZONETYPE_INDUSTRIAL(45),
	ZONETYPE_INDUSTRIAL_FARMLAND(46),
	ZONETYPE_INDUSTRIAL_MED(47),
	ZONETYPE_INDUSTRIAL_HIGH(48),
	ZONETYPE_INDUSTRIAL_CUSTOM(49),
	ZONETYPE_NONSTANDARD(50),
	ZONETYPE_PARK(51),
	ZONETYPE_PUBLIC(52),
	ZONETYPE_TRANSPORT_FACILITIES(53),
	ZONETYPE_PREDEFINED(54),
	ZONETYPE_SPECIAL(55);
	
	private ItemClickEvents(int ord) {
		ordinal = ord;
	}
	
	private int ordinal;
	
	public int getOrdinal() {
		return ordinal;
	}
}
