name: CityBuilder
main: com.d3t.citybuilder.framework.CBMain
version: 0.0.3
api-version: 1.15
depend: [NBTAPI]
softdepend: [Vault, ActionBarAPI]

permissions:
   citybuilder.templateperm:
      description: Template permission
      default: false 

commands:
   foundcity:
      description: Founds a new city at your position
      usage: /<foundcity> <name>
      permission: citybuilder.city.create
      permission-message: You don't have permission to found a city!
   opencityeditor:
      description: ...
      usage: /<templatecommand> [...]
      permission: citybuilder.city.edit
      permission-message: You don't have permission to use this command
   createstructure:
      description: Begins creation of a structure file for use in cities
      usage: /<createstructure> <name> [category] [parameter]
      permission: citybuilder.structures.create
      permission-message: You don't have permission to use this command
   buildstructure:
      description: Starts construction of a building in the current zone
      usage: /<buildstructure> <name> [heading]
      permission: citybuilder.city.edit
      permission-message: You don't have permission to use this command
   reloadstructurefiles:
      description: Reloads all structures from the file system
      usage: /<reloadstructurefiles>
      permission: citybuilder.structures.reload
      permission-message: You don't have permission to use this command
   verifystructure:
      description: Verifies the integrity of a structure file
      usage: /<verifystructure>
      permission: citybuilder.structures.verify
      permission-message: You don't have permission to use this command
   savecities:
      description: Saves the current state of all cities on the server
      usage: /<savecities>
      permission: citybuilder.city.save
      permission-message: You don't have permission to use this command
   loadcities:
      description: Reloads all cities from the file system
      usage: /<loadcities>
      permission: citybuilder.city.load
      permission-message: You don't have permission to use this command
   zoneinfo:
      description: Shows debug information for zones
      usage: /<zoneinfo>
      permission: citybuilder.city.info
      permission-message: You don't have permission to use this command
   realestatescan:
      description: Shows debug information for zones
      usage: /<realestatescan>
      permission: citybuilder.city.info
      permission-message: You don't have permission to use this command
   realestatescan_nonchunk:
      description: Shows debug information for zones
      usage: /<realestatescan_nonchunk>
      permission: citybuilder.city.info
      permission-message: You don't have permission to use this command